name: Cleanup Registry

on:
  workflow_dispatch:
    inputs:
      names:
        description: "packages to process"
        required: true
        type: string
jobs:
  cleanup:
    runs-on: ubuntu-20.04
    steps:
      # - name: Get Repo List
      #   id: repo
      #   uses: yi-Xu-0100/repo-list-generator@v1.0.1
      - uses: smartsquaregmbh/delete-old-packages@v0.5.0
        with:
          token: ${{ secrets.REGISTRY_TOKEN }}
          user: ad2ien
          keep: 1
          type: container
            # ${{steps.repo.outputs.repoList}}
          names: |
            ${{ inputs.names }}
