name: Follow contributor

on:
  pull_request:
    branches: [main]

  workflow_dispatch:
    
jobs:
  follow-user:
    runs-on: ubuntu-20.04
    steps:
      - name: Follow user
        uses: ad2ien/follow-contributor-action-ts@v0.2
        with:
          username: hleonardtek
          token: ${{ secrets.FOLLOW_TOKEN }}
