name: Spell checking
on:
  push:

jobs:
  spelling:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: check-spelling/check-spelling@main
        id: spelling
        with:
          experimental_apply_changes_via_bot: 1
